### ISSUE TITLE
 Module maintained

### ISSUE THREAD

**Issue by AgenceUpMotion** [heimrichhannot/contao-file-manager-bundle#1]
Hello,
I wanted to know if this module was still maintained?
Is it the only one that allows you to create a frontend file manager?
Regards,

**Comment by koertho** [comment]
Hi, yeah, we still use it, but just in few projects, so there are not often updates. But yes, it is maintained :)
Don't know if there are other extension, I think the best place to start searching is https://extensions.contao.org/ ;)
